#!/usr/bin/env bash
if [[ -z $STOW_FOLDERS ]]; then
    export STOW_FOLDERS="autorandr,bin,action-hub,kitty,i3,zsh,fonts,rofi,fonts,fzf,vim,nvim,git,dunst,pi,picom"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

