#!/usr/bin/env bash
if [[ -z $STOW_FOLDERS ]]; then
    export STOW_FOLDERS="autorandr,bin,kitty,i3,zsh,fonts,rofi,fonts,fzf,vim,nvim,git"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

