#!/usr/bin/env zsh

# General 
alias ff='fzm'
alias ffp='fzm | open-project-nvim'
alias www="cd /var/www"
alias vim="nvim"
alias s="kitty +kitten ssh"

# JS
alias pn='pnpm'

# PHP
alias cda="composer dump-autoload"
alias pa="php artisan"

# Git
alias gc='git add . && git commit -m'

# Utils
alias img="kitty +kitten icat"
alias copy="kitty +kitten clipboard"

# Other
# shellcheck disable=SC2142
alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"

alias dotFileInstall="$DOTFILES/install"
