bar {
    status_command     i3status
    tray_output        none
    font               pango:FiraCode Nerd Font 11
    separator_symbol   " | "
    workspace_min_width 40
    strip_workspace_numbers no

    colors {
        background #232634
        statusline #c6d0f5
        separator  #414559

        focused_workspace  #589cf5 #589cf5 #c6d0f5
        active_workspace   #303446 #303446 #c6d0f5
        inactive_workspace #232634 #232634 #888888
        urgent_workspace   #e78284 #e78284 #ffffff
    }
}
