font pango:FiraCode Nerd Font 11

# Catppuccin Frappé
set $rosewater #f2d5cf
set $flamingo  #eebebe
set $pink      #f4b8e4
set $mauve     #ca9ee6
set $red       #e78284
set $maroon    #ea999c
set $peach     #ef9f76
set $green     #a6d189
set $teal      #81c8be
set $sky       #99d1db
set $sapphire  #85c1dc
set $blue      #8caaee
set $lavender  #babbf1
set $text      #c6d0f5
set $subtext1  #b5bfe2
set $subtext0  #a5adce
set $overlay2  #949cbb
set $overlay1  #838ba7
set $overlay0  #737994
set $surface2  #626880
set $surface1  #51576d
set $surface0  #414559
set $base      #303446
set $mantle    #292c3c
set $crust     #232634

# class                   border   backgr.  text     indicator  child_border
client.focused            #589cf5  #589cf5  #ffffff  #2e9ef4    #589cf5
client.focused_inactive   $base    $base    $text    #2e9ef4    $base
client.unfocused          #1c2836  #1c2836  $surface1 #2e9ef4   #1c2836
client.urgent             #e78284  #e78284  #ffffff  #2e9ef4    #e78284
client.background         $base
