floating_modifier $mod

default_border none
default_floating_border none

for_window [class="^kittyfast_"] move scratchpad
for_window [class="^.*"] title_window_icon no
for_window [class="^.*"] title_format " %title"
# for_window [floating] border pixel 2

focus_follows_mouse no
popup_during_fullscreen smart
focus_on_window_activation focus

# gaps inner 4
# gaps outer 0
