set $wsMainCode      "1: Code"
set $wsAIAgent       "2: AI Agent"
set $wsTerminals     "3: Terminals"
set $wsBrowser       "9: Browser"
set $wsMessagers     "10: Communication"

workspace $wsMainCode         output $codeMonitor
workspace $wsBrowser          output $otherMonitor
workspace $wsTerminals        output $otherMonitor
workspace $wsAIAgent          output $otherMonitor
workspace $wsMessagers        output $otherMonitor

workspace_auto_back_and_forth no

assign [class="^Google-chrome$"]      → $wsBrowser
assign [class="^Code$"]               → $wsMainCode
assign [class="^nvim$"]               → $wsMainCode
assign [class="^jetbrains-webstorm$"] → $wsMainCode
assign [class="^jetbrains-phpstorm$"] → $wsMainCode
assign [class="^kitty$"]              → $wsTerminals
assign [class="^Cursor$"]             → $wsAIAgent
assign [class="Telegram"]             → $wsMessagers
assign [class="Slack"]                → $wsMessagers
assign [class="discord"]              → $wsMessagers
